[package]
name = "kimchi"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
bench = false # needed for criterion (https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options)

[dependencies]
ark-ff = { version = "0.3.0", features = [ "parallel", "asm" ] }
ark-ec = { version = "0.3.0", features = [ "parallel" ] }
ark-poly = { version = "0.3.0", features = [ "parallel" ] }
ark-serialize = "0.3.0"
array-init = "1.0.0"
colored = "2.0.0"
rand = "0.8.0"
rand_core = { version = "0.5" }
rayon = "1.5.0"
rmp-serde = "0.15.5"
serde = "1.0.130"
serde_with = "1.10.0"
sprs = "0.9.2"

commitment_dlog = { path = "../commitment" }
groupmap = { path = "../../groupmap" }
mina-curves = { path = "../../curves" }
o1-utils = { path = "../../utils" }
oracle = { path = "../../oracle" }
kimchi-circuits = { path = "../../circuits/kimchi" }

ocaml = { version = "0.22.2", optional = true }
ocaml-gen = { path = "../../ocaml/ocaml-gen", optional = true}

[dev-dependencies]
# benchmarks
criterion = "0.3"
iai = "0.1"

[[bench]]
name = "proof_criterion"
harness = false

[[bench]]
name = "proof_iai"
harness = false

[features]
default = []
ocaml_types = [ "ocaml", "ocaml-gen", "kimchi-circuits/ocaml_types", "commitment_dlog/ocaml_types" ]
